variables:
  VERSION: $(python3 -c "from xml.etree.ElementTree import parse; print(parse(\'${BACK_DIR_NAME}/pom.xml\').getroot().find(\'./{*}version\').text)")

image: docker:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY --

services:
  - docker:dind

stages:
  - build_publish

build-docker-image:
  stage: build_publish
  script:
    - docker build -t qualityobjects/h3lp3r-back:$VERSION .
    - docker push "$CI_REGISTRY_IMAGE:$VERSION"
  only:
    - master


