variables:
  VERSION: latest

image: docker:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY --

stages:
  - build
  - publish

build-docker-image:
  stage: build
  script:
    - docker build -t qualityobjects/h3lp3r-back:$VERSION .
  only:
    - master

publish-docker-image:
  stage: build
  script:        
    - docker push "$CI_REGISTRY_IMAGE:$VERSION"
  only:
    - master

    