management:
  health:
    ldap:
      enabled: false
    db:
      enabled: true
    mail:
      enabled: false
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

spring:
  application:
    name: H3lp3r
  output:
    ansi:
      enabled: always
  jackson:    
    time-zone: Europe/Madrid      
    serialization:
      indent-output: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: true
  elasticsearch:
    rest:
      uris: ${elasticsearch-url:localhost:9200}

server:
  port: ${server-port:8080}
  error:
    whitelabel:
      enabled: false 
  
services:
  url:
    prefix: /api
      